/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/character.glb 
Author: Game Extractor (https://sketchfab.com/GameExtractor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ellen-zenless-zone-zero-game-character-744da39eb1d3437491f68764ea1543bf
Title: Ellen | Zenless Zone Zero Game Character
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/character.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes['���������_mesh_���_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['���������_mesh_���_0_1'].geometry} material={materials.material_1} />
            <mesh geometry={nodes['���������_mesh_���_0_2'].geometry} material={materials.material_2} />
            <mesh geometry={nodes['���������_mesh_���_0_3'].geometry} material={materials.material_3} />
            <mesh geometry={nodes['���������_mesh_���������_0'].geometry} material={materials.material_4} />
            <mesh geometry={nodes['���������_mesh_������_0'].geometry} material={materials.material_5} />
            <mesh geometry={nodes['���������_mesh_���_0_4'].geometry} material={materials.material_6} />
            <mesh geometry={nodes['���������_mesh_������_0_1'].geometry} material={materials.material_7} />
            <mesh geometry={nodes['���������_mesh_������2_0'].geometry} material={materials.material_8} />
            <mesh geometry={nodes['���������_mesh_���_0_5'].geometry} material={materials.material_9} />
            <mesh geometry={nodes['���������_mesh_���_0_6'].geometry} material={materials.material_10} />
            <mesh geometry={nodes['���������_mesh_���_0_7'].geometry} material={materials.material_11} />
            <mesh geometry={nodes['���������_mesh_���_0_8'].geometry} material={materials.material_12} />
            <mesh geometry={nodes['���������_mesh_���_0_9'].geometry} material={materials.material_13} />
            <mesh geometry={nodes['���������_mesh_������_0_2'].geometry} material={materials.material_14} />
            <mesh geometry={nodes['���������_mesh_������+_0'].geometry} material={materials.material_15} />
            <mesh geometry={nodes['���������_mesh_������_0_3'].geometry} material={materials.material_16} />
            <mesh geometry={nodes['���������_mesh_������_0_4'].geometry} material={materials.material_17} />
            <mesh geometry={nodes['���������_mesh_������_0_5'].geometry} material={materials.material_18} />
            <mesh geometry={nodes['���������_mesh_������+_0_1'].geometry} material={materials.material_19} />
            <mesh geometry={nodes['���������_mesh_������_0_6'].geometry} material={materials.material_20} />
            <mesh geometry={nodes['���������_mesh_������_0_7'].geometry} material={materials.material_21} />
            <mesh geometry={nodes['���������_mesh_������_0_8'].geometry} material={materials.material_22} />
            <mesh geometry={nodes['���������_mesh_������_0_9'].geometry} material={materials.material_23} />
            <mesh geometry={nodes['���������_mesh_���������_0_1'].geometry} material={materials.material_24} />
            <mesh geometry={nodes['���������_mesh_���_0_10'].geometry} material={materials.material_25} />
            <mesh geometry={nodes['���������_mesh_������_0_10'].geometry} material={materials.material_26} />
            <mesh geometry={nodes['���������_mesh_������_0_11'].geometry} material={materials.material_27} />
            <mesh geometry={nodes['���������_mesh_���_0_11'].geometry} material={materials.material_28} />
            <mesh geometry={nodes['���������_mesh_������_0_12'].geometry} material={materials.material_29} />
            <mesh geometry={nodes['���������_mesh_������_0_13'].geometry} material={materials.material_30} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/character.glb')
